"""
Day 7 Task 5 — stability / repeated-run tests.

Tests the generic, reusable core (`run_repeated`, `RepeatedRunResult`) and
the two concrete observation builders with synthetic inputs. The artifact
itself (`artifacts/day07/stability_report.md`) is generated by
`scripts/day07_generate_stability_report.py`, driving the real pipeline
against a scripted fake gateway - exercised by actually running that
script (see evals/README.md), not re-simulated here; these tests cover
the library code the script depends on.
"""
from __future__ import annotations

import pytest

from aico.evals.dataset import GoldenCase
from aico.evals.groundedness import GroundednessEvaluation, GroundednessEvaluationFailure, GroundednessVerdict
from aico.evals.stability import (
    STABILITY_REPEAT_COUNT,
    STABILITY_SUBSET_CASE_IDS,
    RepeatedRunResult,
    build_stability_summary,
    observe_groundedness_run,
    observe_refusal_run,
    run_repeated,
)
from aico.rag.answer_service import Blocked, GroundedAnswer, InsufficientEvidence


# ── Design decision sanity ────────────────────────────────────────────

def test_repeat_count_is_greater_than_one_and_matches_module_default():
    assert STABILITY_REPEAT_COUNT > 1


def test_subset_has_no_duplicate_case_ids():
    assert len(STABILITY_SUBSET_CASE_IDS) == len(set(STABILITY_SUBSET_CASE_IDS))


def test_subset_is_documented_against_the_real_golden_dataset():
    import pathlib

    from aico.evals.dataset import load_dataset

    dataset = load_dataset(pathlib.Path(__file__).resolve().parents[1] / "evals" / "golden_v1.json")
    ids = {c.case_id for c in dataset.cases}
    missing = set(STABILITY_SUBSET_CASE_IDS) - ids
    assert not missing, f"stability subset references unknown case id(s): {missing}"

    cases_by_id = {c.case_id: c for c in dataset.cases}
    categories = {cases_by_id[cid].category for cid in STABILITY_SUBSET_CASE_IDS}
    assert "adversarial" not in categories  # justified exclusion, see module docstring


# ── run_repeated / RepeatedRunResult ─────────────────────────────────

def test_run_repeated_calls_run_once_exactly_repeat_count_times():
    calls = []

    def _run_once(i):
        calls.append(i)
        return {"value": i}

    result = run_repeated("C-1", _run_once, repeat_count=4)
    assert calls == [0, 1, 2, 3]
    assert result.repetitions == 4
    assert len(result.observations) == 4


def test_run_repeated_rejects_a_repeat_count_of_one_or_fewer():
    with pytest.raises(ValueError, match="greater than one"):
        run_repeated("C-1", lambda i: {}, repeat_count=1)
    with pytest.raises(ValueError, match="greater than one"):
        run_repeated("C-1", lambda i: {}, repeat_count=0)


def test_numeric_summary_computes_mean_min_max():
    result = RepeatedRunResult(case_id="C", repetitions=4, observations=(
        {"latency_ms": 10.0}, {"latency_ms": 20.0}, {"latency_ms": 30.0}, {"latency_ms": 40.0},
    ))
    summary = result.numeric_summary("latency_ms")
    assert summary == {"mean": 25.0, "min": 10.0, "max": 40.0, "n": 4}


def test_numeric_summary_excludes_booleans_and_missing_fields():
    result = RepeatedRunResult(case_id="C", repetitions=3, observations=(
        {"passed": True}, {"passed": False}, {"other": 1},
    ))
    assert result.numeric_summary("passed") is None  # bools deliberately excluded
    assert result.numeric_summary("nonexistent") is None


def test_rate_summary_computes_fraction_true():
    result = RepeatedRunResult(case_id="C", repetitions=5, observations=(
        {"passed": True}, {"passed": True}, {"passed": True}, {"passed": False}, {"passed": False},
    ))
    summary = result.rate_summary("passed")
    assert summary == {"rate": 0.6, "n": 5}


def test_rate_summary_none_when_field_never_boolean():
    result = RepeatedRunResult(case_id="C", repetitions=2, observations=({"x": 1}, {"x": 2}))
    assert result.rate_summary("x") is None


def test_categorical_summary_reports_counts_and_stability():
    stable = RepeatedRunResult(case_id="C", repetitions=3, observations=(
        {"kind": "a"}, {"kind": "a"}, {"kind": "a"},
    ))
    assert stable.categorical_summary("kind") == {"counts": {"a": 3}, "distinct": 1, "stable": True}

    unstable = RepeatedRunResult(case_id="C", repetitions=3, observations=(
        {"kind": "a"}, {"kind": "b"}, {"kind": "a"},
    ))
    summary = unstable.categorical_summary("kind")
    assert summary["counts"] == {"a": 2, "b": 1}
    assert summary["distinct"] == 2
    assert summary["stable"] is False


def test_categorical_summary_on_a_field_never_observed_is_empty_and_stable():
    # Vacuously "stable" (nothing varied because nothing was observed) -
    # distinct from a genuinely-repeated-and-identical field, but never
    # misreported as unstable.
    result = RepeatedRunResult(case_id="C", repetitions=2, observations=({}, {}))
    summary = result.categorical_summary("missing_field")
    assert summary == {"counts": {}, "distinct": 0, "stable": True}


# ── observe_refusal_run ──────────────────────────────────────────────

def _case(**overrides) -> GoldenCase:
    defaults = dict(
        case_id="T-1", category="answerable", split="train", question="q",
        expected_sources=(), answerability="answerable", critical_facts=(), prohibited_claims=(),
    )
    defaults.update(overrides)
    return GoldenCase(**defaults)


def test_observe_refusal_run_records_kind_pass_and_citation_count():
    case = _case()
    good = GroundedAnswer(question="q", answer="a", citation_ids=("c1", "c2"), confidence_label="high", retrieved_ids=("c1", "c2"))
    row = observe_refusal_run(case, good)
    assert row == {"result_kind": "grounded_answer", "passed": True, "citation_count": 2}


def test_observe_refusal_run_omits_citation_count_when_result_has_none():
    case = _case(category="unanswerable", answerability="unanswerable")
    result = InsufficientEvidence(question="q", explanation="no evidence", retrieved_ids=())
    row = observe_refusal_run(case, result)
    assert "citation_count" not in row
    assert row["passed"] is True


def test_observe_refusal_run_uses_attack_outcome_for_adversarial_cases():
    case = _case(category="adversarial", answerability="must_refuse")
    result = Blocked(question="q", reason="blocked", category="instruction_override")
    row = observe_refusal_run(case, result)
    assert row["result_kind"] == "blocked"
    assert row["passed"] is True


# ── observe_groundedness_run ──────────────────────────────────────────

def test_observe_groundedness_run_records_evaluation_fields():
    verdict = GroundednessVerdict(grounded=True, confidence="high", reasoning="ok")
    evaluation = GroundednessEvaluation(
        case_id="T-1", verdict=verdict, evaluator_model_alias="alias", evaluator_prompt_version="1.0", latency_ms=3.2,
    )
    row = observe_groundedness_run(evaluation)
    assert row == {"outcome_kind": "evaluation", "grounded": True, "confidence": "high", "latency_ms": 3.2}


def test_observe_groundedness_run_records_failure_category():
    failure = GroundednessEvaluationFailure(case_id="T-1", failure_type="evaluator", stage="gateway", category="timeout", message="boom")
    row = observe_groundedness_run(failure)
    assert row == {"outcome_kind": "failure", "failure_category": "timeout"}


# ── end-to-end with run_repeated ─────────────────────────────────────

def test_run_repeated_end_to_end_with_observe_refusal_run_detects_instability():
    case = _case(category="synonym_heavy", answerability="answerable")
    outcomes = [
        GroundedAnswer(question="q", answer="a", citation_ids=("c1",), confidence_label="high", retrieved_ids=("c1",)),
        InsufficientEvidence(question="q", explanation="no", retrieved_ids=()),
        GroundedAnswer(question="q", answer="a", citation_ids=("c1",), confidence_label="high", retrieved_ids=("c1",)),
    ]

    def _run_once(i):
        return observe_refusal_run(case, outcomes[i])

    result = run_repeated(case.case_id, _run_once, repeat_count=3)
    rate = result.rate_summary("passed")
    kind = result.categorical_summary("result_kind")
    assert rate["rate"] == pytest.approx(2 / 3)
    assert kind["stable"] is False
    assert kind["distinct"] == 2


# ── build_stability_summary (Task 11 — embedded in evaluation_report.json) ──

def test_build_stability_summary_reports_pass_rate_and_stability_per_case():
    stable_result = RepeatedRunResult(case_id="A", repetitions=3, observations=(
        {"result_kind": "grounded_answer", "passed": True},
        {"result_kind": "grounded_answer", "passed": True},
        {"result_kind": "grounded_answer", "passed": True},
    ))
    unstable_result = RepeatedRunResult(case_id="B", repetitions=3, observations=(
        {"result_kind": "grounded_answer", "passed": True},
        {"result_kind": "insufficient_evidence", "passed": False},
        {"result_kind": "grounded_answer", "passed": True},
    ))

    summary = build_stability_summary([stable_result, unstable_result], [])
    assert summary["repeat_count"] == STABILITY_REPEAT_COUNT
    assert summary["subset_case_ids"] == list(STABILITY_SUBSET_CASE_IDS)
    sut = {c["case_id"]: c for c in summary["system_under_test"]}
    assert sut["A"] == {"case_id": "A", "pass_rate": 1.0, "stable": True}
    assert sut["B"]["pass_rate"] == pytest.approx(2 / 3)
    assert sut["B"]["stable"] is False


def test_build_stability_summary_reports_grounded_rate_for_evaluator_results():
    grounded_stable = RepeatedRunResult(case_id="C", repetitions=2, observations=(
        {"grounded": True, "confidence": "high"}, {"grounded": True, "confidence": "high"},
    ))
    grounded_unstable = RepeatedRunResult(case_id="D", repetitions=2, observations=(
        {"grounded": True, "confidence": "high"}, {"grounded": False, "confidence": "high"},
    ))

    summary = build_stability_summary([], [grounded_stable, grounded_unstable])
    ev = {c["case_id"]: c for c in summary["evaluator"]}
    assert ev["C"] == {"case_id": "C", "grounded_rate": 1.0, "stable": True}
    assert ev["D"]["grounded_rate"] == pytest.approx(0.5)
    assert ev["D"]["stable"] is False


def test_build_stability_summary_is_json_serializable():
    import json

    result = RepeatedRunResult(case_id="A", repetitions=1, observations=({"result_kind": "grounded_answer", "passed": True},))
    summary = build_stability_summary([result], [])
    json.dumps(summary)  # must not raise
