"""
Day 7 Task 10 — controlled regression proof.

Run: uv run python scripts/day07_controlled_regression_proof.py

Runs the real gate (`aico.evals.day07.main`, the exact command Task 9
built) three times in sequence, each against its own isolated temp
`--artifacts-dir` so this script never touches the committed
`artifacts/day07/evaluation_report.*` — only `controlled_regression.md`
itself is written to the real `artifacts/day07/`:

1. **normal approved configuration** (`--top-k 5`, the committed
   default) → expected PASS
2. **weakened retrieval** (`--top-k 1`) → expected FAIL, non-zero exit
3. **restored approved configuration** (`--top-k 5` again) → expected PASS

The "weakened configuration" is a single CLI flag, not an edited source
file or committed config — reversible by construction, and literally the
first example the brief itself names ("smaller top-k"). Nothing about the
approved configuration changes: the same `evals/golden_v1.json`,
`thresholds_v1.json`, and `baseline_v1.json` are read in all three runs;
only the retrieval window size passed to `BM25Retriever` (and to Task 3's
scorers, which use the identical value) shrinks and then is restored.

`top-k 1` (not 2 or 3) is used deliberately: it fails three independent
thresholds at once (`hit_at_k`, `mrr`, `refusal_accuracy_rate` — see the
generated report) rather than one borderline metric, so the proof isn't
sensitive to a single number sitting just below its floor.

This script asserts its own expected sequence (PASS/FAIL/PASS) before
writing anything — a broken proof fails loudly here rather than silently
committing a wrong narrative.
"""
from __future__ import annotations

import contextlib
import io
import json
import pathlib
import tempfile

from aico.evals import day07

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DATASET_PATH = REPO_ROOT / "evals" / "golden_v1.json"
THRESHOLDS_PATH = REPO_ROOT / "evals" / "thresholds_v1.json"
BASELINE_PATH = REPO_ROOT / "evals" / "baseline_v1.json"
INDEX_DIR = REPO_ROOT / "data" / "index"
OUT_PATH = REPO_ROOT / "artifacts" / "day07" / "controlled_regression.md"
SCRIPT_NAME = "scripts/day07_controlled_regression_proof.py"

APPROVED_TOP_K = day07.DEFAULT_TOP_K  # 5 - the committed, approved configuration
WEAKENED_TOP_K = 1  # deliberately weakened - see module docstring


def _run(top_k: int, artifacts_dir: pathlib.Path) -> tuple[int, dict, str]:
    argv = [
        "--dataset", str(DATASET_PATH), "--thresholds", str(THRESHOLDS_PATH),
        "--baseline", str(BASELINE_PATH), "--index", str(INDEX_DIR),
        "--artifacts-dir", str(artifacts_dir), "--top-k", str(top_k),
    ]
    stdout = io.StringIO()
    with contextlib.redirect_stdout(stdout):
        exit_code = day07.main(argv)
    report = json.loads((artifacts_dir / "evaluation_report.json").read_text(encoding="utf-8"))
    return exit_code, report, stdout.getvalue()


def _fmt(value: float | None) -> str:
    return f"{value:.4f}" if value is not None else "not measured"


def _phase_section(title: str, top_k: int, exit_code: int, report: dict) -> list[str]:
    verdict = "PASS" if report["gate_verdict"]["passed"] else "FAIL"
    lines = [f"## {title}", "", f"`--top-k {top_k}` — **{verdict}**, exit code `{exit_code}`", ""]
    lines.append("| metric | value | min | passed |")
    lines.append("|---|---|---|---|")
    for c in report["threshold_comparison"]:
        lines.append(f"| {c['name']} | {_fmt(c['value'])} | {c['min']:.4f} | {'yes' if c['passed'] else '**NO**'} |")
    lines.append("")
    if report["safety_gate"]["failures"]:
        lines.append(f"Safety failures: {len(report['safety_gate']['failures'])}")
    else:
        lines.append("Safety failures: none")
    lines.append("")
    return lines


def render(
    normal: tuple[int, dict], weakened: tuple[int, dict], restored: tuple[int, dict],
) -> str:
    normal_exit, normal_report = normal
    weakened_exit, weakened_report = weakened
    restored_exit, restored_report = restored

    failed_thresholds = [c["name"] for c in weakened_report["threshold_comparison"] if not c["passed"]]

    lines: list[str] = []
    lines.append("# Day 7 — Controlled Regression Proof")
    lines.append("")
    lines.append(
        f"Generated by `{SCRIPT_NAME}`, driving the real `python -m aico.evals.day07` gate three times "
        f"against the real `evals/golden_v1.json`, `thresholds_v1.json`, and `baseline_v1.json` — nothing "
        f"hand-transcribed. **What changed**: only the `--top-k` CLI flag (retrieval window size passed to "
        f"`BM25Retriever` and to Task 3's scorers), between three values: "
        f"`{APPROVED_TOP_K}` (approved) → `{WEAKENED_TOP_K}` (deliberately weakened) → `{APPROVED_TOP_K}` "
        f"(restored). No source file, threshold, or baseline was edited — this is a reversible, test-only "
        f"CLI override, exactly the brief's own first example (\"smaller top-k\")."
    )
    lines.append("")

    lines.extend(_phase_section("1. Normal approved configuration (baseline result)", APPROVED_TOP_K, normal_exit, normal_report))
    lines.extend(_phase_section("2. Weakened retrieval (regressed result)", WEAKENED_TOP_K, weakened_exit, weakened_report))
    lines.extend(_phase_section("3. Restored approved configuration (restored result)", APPROVED_TOP_K, restored_exit, restored_report))

    lines.append("## Summary")
    lines.append("")
    lines.append("| phase | `--top-k` | verdict | exit code |")
    lines.append("|---|---|---|---|")
    lines.append(f"| normal (baseline) | {APPROVED_TOP_K} | {'PASS' if normal_report['gate_verdict']['passed'] else 'FAIL'} | `{normal_exit}` |")
    lines.append(f"| weakened (regressed) | {WEAKENED_TOP_K} | {'PASS' if weakened_report['gate_verdict']['passed'] else 'FAIL'} | `{weakened_exit}` |")
    lines.append(f"| restored | {APPROVED_TOP_K} | {'PASS' if restored_report['gate_verdict']['passed'] else 'FAIL'} | `{restored_exit}` |")
    lines.append("")
    lines.append(f"Failed threshold(s) under the weakened configuration: {', '.join(failed_thresholds)}.")
    lines.append("")
    lines.append(
        "The restored run used the exact same `--top-k` value as the normal run and produced an identical "
        "verdict — the regression was entirely reversible by undoing the one flag that caused it, proving "
        "the weakening was test-only, not a change to the approved configuration itself."
    )
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = pathlib.Path(tmp)
        normal_exit, normal_report, _ = _run(APPROVED_TOP_K, tmp_path / "normal")
        weakened_exit, weakened_report, _ = _run(WEAKENED_TOP_K, tmp_path / "weakened")
        restored_exit, restored_report, _ = _run(APPROVED_TOP_K, tmp_path / "restored")

    assert normal_exit == 0, f"normal approved configuration did not pass: exit={normal_exit}"
    assert weakened_exit != 0, f"weakened retrieval did not fail: exit={weakened_exit}"
    assert restored_exit == 0, f"restored approved configuration did not pass: exit={restored_exit}"

    report_md = render((normal_exit, normal_report), (weakened_exit, weakened_report), (restored_exit, restored_report))
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(report_md, encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    print(f"normal: exit={normal_exit} pass={normal_report['gate_verdict']['passed']}")
    print(f"weakened: exit={weakened_exit} pass={weakened_report['gate_verdict']['passed']}")
    print(f"restored: exit={restored_exit} pass={restored_report['gate_verdict']['passed']}")


if __name__ == "__main__":
    main()
